# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shz/jni

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shz/jni

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shz/jni/CMakeFiles /home/shz/jni/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shz/jni/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/main.cpp.s
.PHONY : main.cpp.s

src/AngleDetect.o: src/AngleDetect.cpp.o
.PHONY : src/AngleDetect.o

# target to build an object file
src/AngleDetect.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/AngleDetect.cpp.o
.PHONY : src/AngleDetect.cpp.o

src/AngleDetect.i: src/AngleDetect.cpp.i
.PHONY : src/AngleDetect.i

# target to preprocess a source file
src/AngleDetect.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/AngleDetect.cpp.i
.PHONY : src/AngleDetect.cpp.i

src/AngleDetect.s: src/AngleDetect.cpp.s
.PHONY : src/AngleDetect.s

# target to generate assembly for a file
src/AngleDetect.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/AngleDetect.cpp.s
.PHONY : src/AngleDetect.cpp.s

src/Bitmap.o: src/Bitmap.cpp.o
.PHONY : src/Bitmap.o

# target to build an object file
src/Bitmap.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Bitmap.cpp.o
.PHONY : src/Bitmap.cpp.o

src/Bitmap.i: src/Bitmap.cpp.i
.PHONY : src/Bitmap.i

# target to preprocess a source file
src/Bitmap.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Bitmap.cpp.i
.PHONY : src/Bitmap.cpp.i

src/Bitmap.s: src/Bitmap.cpp.s
.PHONY : src/Bitmap.s

# target to generate assembly for a file
src/Bitmap.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Bitmap.cpp.s
.PHONY : src/Bitmap.cpp.s

src/Calibration.o: src/Calibration.cpp.o
.PHONY : src/Calibration.o

# target to build an object file
src/Calibration.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Calibration.cpp.o
.PHONY : src/Calibration.cpp.o

src/Calibration.i: src/Calibration.cpp.i
.PHONY : src/Calibration.i

# target to preprocess a source file
src/Calibration.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Calibration.cpp.i
.PHONY : src/Calibration.cpp.i

src/Calibration.s: src/Calibration.cpp.s
.PHONY : src/Calibration.s

# target to generate assembly for a file
src/Calibration.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Calibration.cpp.s
.PHONY : src/Calibration.cpp.s

src/TimeUtils.o: src/TimeUtils.cpp.o
.PHONY : src/TimeUtils.o

# target to build an object file
src/TimeUtils.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/TimeUtils.cpp.o
.PHONY : src/TimeUtils.cpp.o

src/TimeUtils.i: src/TimeUtils.cpp.i
.PHONY : src/TimeUtils.i

# target to preprocess a source file
src/TimeUtils.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/TimeUtils.cpp.i
.PHONY : src/TimeUtils.cpp.i

src/TimeUtils.s: src/TimeUtils.cpp.s
.PHONY : src/TimeUtils.s

# target to generate assembly for a file
src/TimeUtils.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/TimeUtils.cpp.s
.PHONY : src/TimeUtils.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/AngleDetect.o"
	@echo "... src/AngleDetect.i"
	@echo "... src/AngleDetect.s"
	@echo "... src/Bitmap.o"
	@echo "... src/Bitmap.i"
	@echo "... src/Bitmap.s"
	@echo "... src/Calibration.o"
	@echo "... src/Calibration.i"
	@echo "... src/Calibration.s"
	@echo "... src/TimeUtils.o"
	@echo "... src/TimeUtils.i"
	@echo "... src/TimeUtils.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

